/**
 * Software end-user license agreement.
 *
 * The LICENSE.TXT containing the license is located in the JGPSS project.
 * License.txt can be downloaded here:
 * href="http://www-eio.upc.es/~Pau/index.php?q=node/28
 *
 * NOTICE TO THE USER: BY COPYING, INSTALLING OR USING THIS SOFTWARE OR PART OF
 * THIS SOFTWARE, YOU AGREE TO THE   TERMS AND CONDITIONS OF THE LICENSE AGREEMENT
 * AS IF IT WERE A WRITTEN AGREEMENT NEGOTIATED AND SIGNED BY YOU. THE LICENSE
 * AGREEMENT IS ENFORCEABLE AGAINST YOU AND ANY OTHER LEGAL PERSON ACTING ON YOUR
 * BEHALF.
 * IF, AFTER READING THE TERMS AND CONDITIONS HEREIN, YOU DO NOT AGREE TO THEM,
 * YOU MAY NOT INSTALL THIS SOFTWARE ON YOUR COMPUTER.
 * UPC IS THE OWNER OF ALL THE INTELLECTUAL PROPERTY OF THE SOFTWARE AND ONLY
 * AUTHORIZES YOU TO USE THE SOFTWARE IN ACCORDANCE WITH THE TERMS SET OUT IN
 * THE LICENSE AGREEMENT.
 */

package jgpss;

/**
 *
 * @author  M.Dolores
 */
public class PantallaOpenNewModel extends javax.swing.JDialog {
    
    //per indicar si entrem en modificar
    private boolean consultar = false;
    private boolean modificar = false;
    /** Creates new form PantallaOpenNewModel */
    public PantallaOpenNewModel() {
        this.setModal(true); 
        initComponents();
        this.setTitle(Constants.tituloNewModel);
        botoModify.setVisible(false);
    }
    
    public PantallaOpenNewModel(String nom, String descripcio){
        this.setModal(true);
        initComponents();
        this.setTitle(Constants.tituloNewModel);
        consultar = true;
        botoAcceptar.setVisible(false);
        textDescrpModel.setText(VarGlobals.model.getDescripModel());
        textNomModel.setText(VarGlobals.model.getNomModel());
        textDescrpModel.setEnabled(false);
        textNomModel.setEnabled(false);
        
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        botoCancelar = new javax.swing.JButton();
        textNomModel = new javax.swing.JTextField();
        textDescrpModel = new javax.swing.JTextField();
        botoAcceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botoModify = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        botoCancelar.setText("Cancel");
        botoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoCancelarActionPerformed(evt);
            }
        });

        botoAcceptar.setText("OK");
        botoAcceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoAcceptarActionPerformed(evt);
            }
        });

        jLabel1.setText("Description");

        jLabel2.setText("Name");

        botoModify.setText("Modify");
        botoModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoModifyActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(botoCancelar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 171, Short.MAX_VALUE)
                        .add(botoModify)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(botoAcceptar))
                    .add(textDescrpModel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, textNomModel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(textNomModel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(22, 22, 22)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(textDescrpModel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(39, 39, 39)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(botoCancelar)
                    .add(botoAcceptar)
                    .add(botoModify))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoModifyActionPerformed

        modificar= true;
        botoAcceptar.setVisible(true);
        botoModify.setVisible(false);
         textDescrpModel.setEnabled(true);
        textNomModel.setEnabled(true);
    }//GEN-LAST:event_botoModifyActionPerformed

    private void botoAcceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoAcceptarActionPerformed
    //mirem que tant la s'hagin introduit valors al nom del modl i a la descripci�
     boolean tancar = true;
     
        if(!textNomModel.getText().equals("")){
            if(!textDescrpModel.getText().equals("")){
            //tot correcte
                if(!modificar){
                    VarGlobals.model= new Model();
                    VarGlobals.model.setDescripModel(textDescrpModel.getText());
                    VarGlobals.model.setNomModel(textNomModel.getText());
                    VarGlobals.dg.SetModel(VarGlobals.model);
                    VarGlobals.continuar = true;
                    VarGlobals.esModificat= true;
                }
                else{
                    VarGlobals.model.setDescripModel(textDescrpModel.getText());
                    VarGlobals.model.setNomModel(textNomModel.getText());
                }
            }
            else{
                tancar = cridarError(Constants.ErrorDescripModel);
            }
        
            
        }
        else{
        tancar = cridarError(Constants.ErrorNomModel);
        }
     
     if(tancar){
        setVisible(false);
         dispose();
     
     }
        
    }//GEN-LAST:event_botoAcceptarActionPerformed
/**
 *Si cancelem tornem a la pantalla principal i no fem res
 */
    private void botoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoCancelarActionPerformed
        if(!consultar&&!modificar)
            VarGlobals.continuar=false;
         setVisible(false);
         dispose();
    }//GEN-LAST:event_botoCancelarActionPerformed
  /*
   *funci� que crida a la pantalla d'error
   *i retorna fals per a que no es tanqui la pantalla
   */
   private boolean cridarError(String error){
            PantallaError perror= new PantallaError(error);
            perror.setLocationRelativeTo(this);
        
            perror.setVisible(true);
            perror.dispose();
         
            return false;
   
   }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoAcceptar;
    private javax.swing.JButton botoCancelar;
    private javax.swing.JButton botoModify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textDescrpModel;
    private javax.swing.JTextField textNomModel;
    // End of variables declaration//GEN-END:variables
    
}
